"""empty message

Revision ID: 0449fbb78d3b
Revises: beec22f62983
Create Date: 2021-02-22 10:15:57.481103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0449fbb78d3b'
down_revision = 'beec22f62983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundraiser', sa.Column('city', sa.String(), nullable=True))
    op.add_column('fundraiser', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('fundraiser', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('fundraiser', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('fundraiser', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraiser', 'state')
    op.drop_column('fundraiser', 'contact_phone')
    op.drop_column('fundraiser', 'contact_name')
    op.drop_column('fundraiser', 'contact_email')
    op.drop_column('fundraiser', 'city')
    # ### end Alembic commands ###
