"""empty message

Revision ID: 0ba67a56c0a2
Revises: 857a6a6052ef
Create Date: 2021-01-25 13:55:16.418767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba67a56c0a2'
down_revision = '857a6a6052ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('promo_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'promo_timestamp')
    # ### end Alembic commands ###
