"""empty message

Revision ID: 0f99cf35a2fa
Revises: 9b59d1793827
Create Date: 2021-02-01 16:01:53.885839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f99cf35a2fa'
down_revision = '9b59d1793827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('max_distance', sa.Integer(), server_default='25', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'max_distance')
    # ### end Alembic commands ###
