"""empty message

Revision ID: 16432677d849
Revises: b80bfd01c2af
Create Date: 2019-06-28 15:01:08.444984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16432677d849'
down_revision = 'b80bfd01c2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_confirmed', sa.Boolean(), server_default='f', nullable=False))
    op.alter_column('user', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'influencer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'influencer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user', 'email_confirmed')
    # ### end Alembic commands ###
