"""empty message

Revision ID: 20f9b0904aa0
Revises: 0449fbb78d3b
Create Date: 2021-02-22 10:19:16.529163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f9b0904aa0'
down_revision = '0449fbb78d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundraiser', sa.Column('from_form', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraiser', 'from_form')
    # ### end Alembic commands ###
