"""empty message

Revision ID: 2798c4505a07
Revises: 937cef98727a
Create Date: 2021-02-23 13:54:45.236802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2798c4505a07'
down_revision = '937cef98727a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant', 'name')
    # ### end Alembic commands ###
