"""empty message

Revision ID: 289ad46f33e6
Revises: 20f9b0904aa0
Create Date: 2021-02-22 12:02:33.401109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289ad46f33e6'
down_revision = '20f9b0904aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('business', sa.String(), nullable=True),
    sa.Column('locations', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_contact')
    # ### end Alembic commands ###
