"""empty message

Revision ID: 2b5adc8436a9
Revises: f5e647db3ba2
Create Date: 2021-01-25 11:29:07.376235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5adc8436a9'
down_revision = 'f5e647db3ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundraiser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('team_code', sa.String(), nullable=True),
    sa.Column('base_goal', sa.Integer(), nullable=True),
    sa.Column('incentives', sa.String(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('team_code', sa.String(), nullable=True),
    sa.Column('single_use', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('redeemed', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('prepaid', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('fundraiser_id', sa.Integer(), nullable=True),
    sa.Column('six_month', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('twenty_five', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('purchased', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['fundraiser.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_table('promo_code')
    op.drop_table('fundraiser')
    # ### end Alembic commands ###
