"""empty message

Revision ID: 45f136dcbb9f
Revises: a894ffe155ec
Create Date: 2021-02-02 16:35:04.130612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f136dcbb9f'
down_revision = 'a894ffe155ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('header_uri', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('button', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('button_size', sa.Integer(), nullable=True),
    sa.Column('button_top', sa.Integer(), nullable=True),
    sa.Column('button_left', sa.Integer(), nullable=True),
    sa.Column('button_color', sa.String(), nullable=True),
    sa.Column('button_url', sa.String(), nullable=True),
    sa.Column('modal_title', sa.String(), nullable=True),
    sa.Column('modal_info', sa.String(), nullable=True),
    sa.Column('button_text', sa.String(), nullable=True),
    sa.Column('button_text_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region')
    # ### end Alembic commands ###
