"""empty message

Revision ID: 4a93a98b41ac
Revises: 3f59a3db4cd4
Create Date: 2021-02-24 11:53:25.864737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a93a98b41ac'
down_revision = '3f59a3db4cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_contact', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'merchant_contact', 'merchant', ['merchant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('merchant_contact', 'locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_contact', sa.Column('locations', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'merchant_contact', type_='foreignkey')
    op.drop_column('merchant_contact', 'merchant_id')
    # ### end Alembic commands ###
