"""empty message

Revision ID: 5320413b1077
Revises: 3e6fcc4d3086
Create Date: 2021-02-23 16:05:29.524824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5320413b1077'
down_revision = '3e6fcc4d3086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('deleted', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant', 'deleted')
    # ### end Alembic commands ###
