"""empty message

Revision ID: 5cb47b6fccf2
Revises: 4a93a98b41ac
Create Date: 2021-02-24 12:52:19.583494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb47b6fccf2'
down_revision = '4a93a98b41ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundraiser', sa.Column('deleted', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraiser', 'deleted')
    # ### end Alembic commands ###
