"""empty message

Revision ID: 6fda80f9c88d
Revises: d28d4e801904
Create Date: 2021-02-17 12:49:09.732179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fda80f9c88d'
down_revision = 'd28d4e801904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magic_link', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'magic_link', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'magic_link', type_='foreignkey')
    op.drop_column('magic_link', 'user_id')
    # ### end Alembic commands ###
