"""empty message

Revision ID: 7553526f6791
Revises: cd2fcd76f4c8
Create Date: 2021-02-23 11:46:32.295698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7553526f6791'
down_revision = 'cd2fcd76f4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('facebook', sa.String(), nullable=True))
    op.drop_column('merchant', 'longitude')
    op.drop_column('merchant', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('merchant', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('merchant', 'facebook')
    # ### end Alembic commands ###
