"""empty message

Revision ID: 937cef98727a
Revises: 7553526f6791
Create Date: 2021-02-23 12:23:26.322619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937cef98727a'
down_revision = '7553526f6791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('images', sa.JSON(), nullable=True))
    op.drop_column('merchant', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('merchant', 'images')
    # ### end Alembic commands ###
