"""empty message

Revision ID: 96ff5bd73c47
Revises: 5a35ecba7541
Create Date: 2021-01-22 14:14:05.915490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96ff5bd73c47'
down_revision = '5a35ecba7541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('from_', sa.String(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('created_s', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('merchant', sa.Column('created_s', sa.DateTime(), nullable=True))
    op.drop_column('merchant', 'created')
    op.add_column('redemption', sa.Column('created_s', sa.DateTime(), nullable=True))
    op.drop_column('redemption', 'created')
    op.add_column('user', sa.Column('created_s', sa.DateTime(), nullable=True))
    op.drop_column('user', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('user', 'created_s')
    op.add_column('redemption', sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('redemption', 'created_s')
    op.add_column('merchant', sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('merchant', 'created_s')
    op.drop_table('sms_log')
    # ### end Alembic commands ###
