"""empty message

Revision ID: 99e49b971ca9
Revises: 9627408f0648
Create Date: 2021-02-02 13:09:27.376401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e49b971ca9'
down_revision = '9627408f0648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('iap_receipt', sa.String(), nullable=True))
    op.add_column('user', sa.Column('stripe_customer', sa.String(), nullable=True))
    op.add_column('user', sa.Column('stripe_subscription', sa.String(), nullable=True))
    op.drop_column('user', 'stripe_customer_id')
    op.drop_column('user', 'stripe_subscription_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'stripe_subscription')
    op.drop_column('user', 'stripe_customer')
    op.drop_column('user', 'iap_receipt')
    # ### end Alembic commands ###
