"""empty message

Revision ID: 9b59d1793827
Revises: e40c4a735dc9
Create Date: 2021-02-01 15:49:17.182065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b59d1793827'
down_revision = 'e40c4a735dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_subscription_id')
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
