"""empty message

Revision ID: a894ffe155ec
Revises: 99e49b971ca9
Create Date: 2021-02-02 14:30:10.831548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a894ffe155ec'
down_revision = '99e49b971ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'code')
    # ### end Alembic commands ###
