"""empty message

Revision ID: ac1bc821051b
Revises: 6285dc765100
Create Date: 2021-02-18 13:18:06.005382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1bc821051b'
down_revision = '6285dc765100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('foodtruck_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'merchant', ['foodtruck_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'foodtruck_id')
    # ### end Alembic commands ###
