"""empty message

Revision ID: acd4b1edd0e2
Revises: f70519ef507b
Create Date: 2021-02-25 09:19:57.966943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd4b1edd0e2'
down_revision = 'f70519ef507b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('location', sa.Column('reviewed', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('location', sa.Column('sticker', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('location', sa.Column('visited', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('merchant', sa.Column('go_live_text', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('merchant', sa.Column('terms_agreed', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('merchant', sa.Column('welcome_email', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant', 'welcome_email')
    op.drop_column('merchant', 'terms_agreed')
    op.drop_column('merchant', 'go_live_text')
    op.drop_column('location', 'visited')
    op.drop_column('location', 'sticker')
    op.drop_column('location', 'reviewed')
    op.drop_table('location_note')
    # ### end Alembic commands ###
