"""empty message

Revision ID: b79ab857d3b8
Revises: ef0bff6f0ba8
Create Date: 2021-02-03 11:38:31.576952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79ab857d3b8'
down_revision = 'ef0bff6f0ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('is_bogo', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('offer', sa.Column('single_use', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'single_use')
    op.drop_column('offer', 'is_bogo')
    # ### end Alembic commands ###
