"""empty message

Revision ID: bbd24628a3cb
Revises: b79ab857d3b8
Create Date: 2021-02-03 12:04:25.163957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd24628a3cb'
down_revision = 'b79ab857d3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('happy_hour', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'happy_hour')
    # ### end Alembic commands ###
