"""empty message

Revision ID: beec22f62983
Revises: ac1bc821051b
Create Date: 2021-02-22 10:11:30.426811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beec22f62983'
down_revision = 'ac1bc821051b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodtruck_check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('foodtruck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foodtruck_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fundraiser', sa.Column('start', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraiser', 'start')
    op.drop_table('foodtruck_check_in')
    # ### end Alembic commands ###
