"""empty message

Revision ID: e40c4a735dc9
Revises: 3c6daafbb270
Create Date: 2021-02-01 15:35:49.797567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40c4a735dc9'
down_revision = '3c6daafbb270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundraiser_code', sa.Column('all_codes', sa.JSON(), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraiser_code', 'all_codes')
    # ### end Alembic commands ###
